# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'centralperk.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 0, 751, 531))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.label = QtWidgets.QLabel(self.page1)
        self.label.setGeometry(QtCore.QRect(190, 20, 351, 71))
        self.label.setObjectName("label")
        self.usr_edt = QtWidgets.QLineEdit(self.page1)
        self.usr_edt.setGeometry(QtCore.QRect(232, 170, 271, 20))
        self.usr_edt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.usr_edt.setText("")
        self.usr_edt.setObjectName("usr_edt")
        self.pass_edt = QtWidgets.QLineEdit(self.page1)
        self.pass_edt.setGeometry(QtCore.QRect(232, 260, 271, 20))
        self.pass_edt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_edt.setObjectName("pass_edt")
        self.lgn_btn = QtWidgets.QPushButton(self.page1)
        self.lgn_btn.setGeometry(QtCore.QRect(130, 350, 141, 31))
        self.lgn_btn.setObjectName("lgn_btn")
        self.reg_btn = QtWidgets.QPushButton(self.page1)
        self.reg_btn.setGeometry(QtCore.QRect(460, 350, 131, 31))
        self.reg_btn.setObjectName("reg_btn")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.label_10 = QtWidgets.QLabel(self.page2)
        self.label_10.setGeometry(QtCore.QRect(250, 30, 231, 51))
        self.label_10.setObjectName("label_10")
        self.nadmusr_edt = QtWidgets.QLineEdit(self.page2)
        self.nadmusr_edt.setGeometry(QtCore.QRect(210, 140, 331, 20))
        self.nadmusr_edt.setObjectName("nadmusr_edt")
        self.nadmpass_edt = QtWidgets.QLineEdit(self.page2)
        self.nadmpass_edt.setGeometry(QtCore.QRect(210, 210, 331, 20))
        self.nadmpass_edt.setObjectName("nadmpass_edt")
        self.nadmsub_btn = QtWidgets.QPushButton(self.page2)
        self.nadmsub_btn.setGeometry(QtCore.QRect(160, 340, 151, 51))
        self.nadmsub_btn.setObjectName("nadmsub_btn")
        self.nadmbck_btn = QtWidgets.QPushButton(self.page2)
        self.nadmbck_btn.setGeometry(QtCore.QRect(440, 340, 161, 51))
        self.nadmbck_btn.setObjectName("nadmbck_btn")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.label_2 = QtWidgets.QLabel(self.page3)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 351, 41))
        self.label_2.setObjectName("label_2")
        self.newcs_btn = QtWidgets.QPushButton(self.page3)
        self.newcs_btn.setGeometry(QtCore.QRect(200, 100, 331, 41))
        self.newcs_btn.setObjectName("newcs_btn")
        self.uptcs_btn = QtWidgets.QPushButton(self.page3)
        self.uptcs_btn.setGeometry(QtCore.QRect(200, 180, 331, 51))
        self.uptcs_btn.setObjectName("uptcs_btn")
        self.delcs_btn = QtWidgets.QPushButton(self.page3)
        self.delcs_btn.setGeometry(QtCore.QRect(200, 260, 331, 41))
        self.delcs_btn.setObjectName("delcs_btn")
        self.uptf_btn = QtWidgets.QPushButton(self.page3)
        self.uptf_btn.setGeometry(QtCore.QRect(200, 330, 331, 51))
        self.uptf_btn.setObjectName("uptf_btn")
        self.ext_btn = QtWidgets.QPushButton(self.page3)
        self.ext_btn.setGeometry(QtCore.QRect(204, 412, 331, 51))
        self.ext_btn.setObjectName("ext_btn")
        self.dispcs_btn = QtWidgets.QPushButton(self.page3)
        self.dispcs_btn.setGeometry(QtCore.QRect(560, 130, 151, 61))
        self.dispcs_btn.setObjectName("dispcs_btn")
        self.uptf1_btn = QtWidgets.QPushButton(self.page3)
        self.uptf1_btn.setGeometry(QtCore.QRect(560, 40, 151, 71))
        self.uptf1_btn.setObjectName("uptf1_btn")
        self.csgraph_btn = QtWidgets.QPushButton(self.page3)
        self.csgraph_btn.setGeometry(QtCore.QRect(560, 200, 151, 61))
        self.csgraph_btn.setObjectName("csgraph_btn")
        self.foodgraph_btn = QtWidgets.QPushButton(self.page3)
        self.foodgraph_btn.setGeometry(QtCore.QRect(560, 270, 151, 51))
        self.foodgraph_btn.setObjectName("foodgraph_btn")
        self.bevgraph_btn = QtWidgets.QPushButton(self.page3)
        self.bevgraph_btn.setGeometry(QtCore.QRect(560, 330, 151, 61))
        self.bevgraph_btn.setObjectName("bevgraph_btn")
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.ncsname_edt = QtWidgets.QLineEdit(self.page4)
        self.ncsname_edt.setGeometry(QtCore.QRect(120, 120, 331, 20))
        self.ncsname_edt.setObjectName("ncsname_edt")
        self.ncsmbn_edt = QtWidgets.QLineEdit(self.page4)
        self.ncsmbn_edt.setGeometry(QtCore.QRect(120, 190, 331, 20))
        self.ncsmbn_edt.setObjectName("ncsmbn_edt")
        self.label_3 = QtWidgets.QLabel(self.page4)
        self.label_3.setGeometry(QtCore.QRect(210, 40, 321, 51))
        self.label_3.setObjectName("label_3")
        self.ncsadd_edt = QtWidgets.QTextEdit(self.page4)
        self.ncsadd_edt.setGeometry(QtCore.QRect(120, 250, 331, 91))
        self.ncsadd_edt.setObjectName("ncsadd_edt")
        self.ncssub_btn = QtWidgets.QPushButton(self.page4)
        self.ncssub_btn.setGeometry(QtCore.QRect(150, 432, 121, 41))
        self.ncssub_btn.setObjectName("ncssub_btn")
        self.ncsbck_btn = QtWidgets.QPushButton(self.page4)
        self.ncsbck_btn.setGeometry(QtCore.QRect(510, 432, 111, 41))
        self.ncsbck_btn.setObjectName("ncsbck_btn")
        self.calendar = QtWidgets.QCalendarWidget(self.page4)
        self.calendar.setGeometry(QtCore.QRect(480, 140, 256, 183))
        self.calendar.setObjectName("calendar")
        self.stackedWidget.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.uptcsidsub_btn = QtWidgets.QPushButton(self.page5)
        self.uptcsidsub_btn.setGeometry(QtCore.QRect(330, 250, 121, 31))
        self.uptcsidsub_btn.setObjectName("uptcsidsub_btn")
        self.label_11 = QtWidgets.QLabel(self.page5)
        self.label_11.setGeometry(QtCore.QRect(240, 30, 241, 51))
        self.label_11.setObjectName("label_11")
        self.uptcsid_edt = QtWidgets.QLineEdit(self.page5)
        self.uptcsid_edt.setGeometry(QtCore.QRect(230, 120, 281, 20))
        self.uptcsid_edt.setObjectName("uptcsid_edt")
        self.uptcsidbck_btn = QtWidgets.QPushButton(self.page5)
        self.uptcsidbck_btn.setGeometry(QtCore.QRect(334, 320, 111, 31))
        self.uptcsidbck_btn.setObjectName("uptcsidbck_btn")
        self.stackedWidget.addWidget(self.page5)
        self.page6 = QtWidgets.QWidget()
        self.page6.setObjectName("page6")
        self.label_4 = QtWidgets.QLabel(self.page6)
        self.label_4.setGeometry(QtCore.QRect(230, 20, 261, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page6)
        self.label_5.setGeometry(QtCore.QRect(80, 110, 141, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page6)
        self.label_6.setGeometry(QtCore.QRect(350, 110, 131, 31))
        self.label_6.setObjectName("label_6")
        self.food_cmb = QtWidgets.QComboBox(self.page6)
        self.food_cmb.setGeometry(QtCore.QRect(70, 180, 171, 22))
        self.food_cmb.setObjectName("food_cmb")
        self.bev_cmb = QtWidgets.QComboBox(self.page6)
        self.bev_cmb.setGeometry(QtCore.QRect(350, 180, 181, 22))
        self.bev_cmb.setEditable(False)
        self.bev_cmb.setObjectName("bev_cmb")
        self.foodadd_btn = QtWidgets.QPushButton(self.page6)
        self.foodadd_btn.setGeometry(QtCore.QRect(120, 240, 75, 23))
        self.foodadd_btn.setObjectName("foodadd_btn")
        self.bevadd_btn = QtWidgets.QPushButton(self.page6)
        self.bevadd_btn.setGeometry(QtCore.QRect(400, 240, 75, 23))
        self.bevadd_btn.setObjectName("bevadd_btn")
        self.fbbck_btn = QtWidgets.QPushButton(self.page6)
        self.fbbck_btn.setGeometry(QtCore.QRect(70, 390, 191, 51))
        self.fbbck_btn.setObjectName("fbbck_btn")
        self.prcr_btn = QtWidgets.QPushButton(self.page6)
        self.prcr_btn.setGeometry(QtCore.QRect(510, 220, 201, 51))
        self.prcr_btn.setObjectName("prcr_btn")
        self.billdisp_edt = QtWidgets.QTextEdit(self.page6)
        self.billdisp_edt.setGeometry(QtCore.QRect(273, 280, 461, 241))
        self.billdisp_edt.setObjectName("billdisp_edt")
        self.uptcs_lbl = QtWidgets.QLabel(self.page6)
        self.uptcs_lbl.setGeometry(QtCore.QRect(100, 20, 131, 21))
        self.uptcs_lbl.setObjectName("uptcs_lbl")
        self.label_13 = QtWidgets.QLabel(self.page6)
        self.label_13.setGeometry(QtCore.QRect(-10, 20, 101, 20))
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page6)
        self.page7 = QtWidgets.QWidget()
        self.page7.setObjectName("page7")
        self.label_7 = QtWidgets.QLabel(self.page7)
        self.label_7.setGeometry(QtCore.QRect(220, 32, 311, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page7)
        self.label_8.setGeometry(QtCore.QRect(70, 140, 151, 41))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page7)
        self.label_9.setGeometry(QtCore.QRect(490, 140, 161, 41))
        self.label_9.setObjectName("label_9")
        self.nfoodname_edt = QtWidgets.QLineEdit(self.page7)
        self.nfoodname_edt.setGeometry(QtCore.QRect(90, 220, 171, 20))
        self.nfoodname_edt.setObjectName("nfoodname_edt")
        self.nbevname_edt = QtWidgets.QLineEdit(self.page7)
        self.nbevname_edt.setGeometry(QtCore.QRect(492, 220, 191, 20))
        self.nbevname_edt.setObjectName("nbevname_edt")
        self.nfoodprice_edt = QtWidgets.QLineEdit(self.page7)
        self.nfoodprice_edt.setGeometry(QtCore.QRect(90, 290, 171, 20))
        self.nfoodprice_edt.setObjectName("nfoodprice_edt")
        self.nbevprice_edt = QtWidgets.QLineEdit(self.page7)
        self.nbevprice_edt.setGeometry(QtCore.QRect(500, 290, 181, 20))
        self.nbevprice_edt.setObjectName("nbevprice_edt")
        self.nfoodsub_btn = QtWidgets.QPushButton(self.page7)
        self.nfoodsub_btn.setGeometry(QtCore.QRect(120, 362, 121, 41))
        self.nfoodsub_btn.setObjectName("nfoodsub_btn")
        self.nbevsub_btn = QtWidgets.QPushButton(self.page7)
        self.nbevsub_btn.setGeometry(QtCore.QRect(540, 352, 121, 41))
        self.nbevsub_btn.setObjectName("nbevsub_btn")
        self.nfbbck_btn = QtWidgets.QPushButton(self.page7)
        self.nfbbck_btn.setGeometry(QtCore.QRect(320, 410, 131, 51))
        self.nfbbck_btn.setObjectName("nfbbck_btn")
        self.stackedWidget.addWidget(self.page7)
        self.page8 = QtWidgets.QWidget()
        self.page8.setObjectName("page8")
        self.label_12 = QtWidgets.QLabel(self.page8)
        self.label_12.setGeometry(QtCore.QRect(230, 40, 261, 41))
        self.label_12.setObjectName("label_12")
        self.delcs_edt = QtWidgets.QLineEdit(self.page8)
        self.delcs_edt.setGeometry(QtCore.QRect(220, 160, 281, 20))
        self.delcs_edt.setObjectName("delcs_edt")
        self.delcsid_btn = QtWidgets.QPushButton(self.page8)
        self.delcsid_btn.setGeometry(QtCore.QRect(270, 260, 151, 31))
        self.delcsid_btn.setObjectName("delcsid_btn")
        self.delbck_btn = QtWidgets.QPushButton(self.page8)
        self.delbck_btn.setGeometry(QtCore.QRect(270, 340, 151, 31))
        self.delbck_btn.setObjectName("delbck_btn")
        self.stackedWidget.addWidget(self.page8)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setGeometry(QtCore.QRect(236, 19, 251, 31))
        self.label_14.setObjectName("label_14")
        self.dispallcs_edt = QtWidgets.QTextEdit(self.page)
        self.dispallcs_edt.setGeometry(QtCore.QRect(60, 60, 611, 411))
        self.dispallcs_edt.setObjectName("dispallcs_edt")
        self.dispallcs_btn = QtWidgets.QPushButton(self.page)
        self.dispallcs_btn.setGeometry(QtCore.QRect(160, 480, 171, 31))
        self.dispallcs_btn.setObjectName("dispallcs_btn")
        self.dispallcsbck_btn = QtWidgets.QPushButton(self.page)
        self.dispallcsbck_btn.setGeometry(QtCore.QRect(400, 480, 161, 31))
        self.dispallcsbck_btn.setObjectName("dispallcsbck_btn")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(220, 20, 311, 41))
        self.label_15.setObjectName("label_15")
        self.food1_cmb = QtWidgets.QComboBox(self.page_2)
        self.food1_cmb.setGeometry(QtCore.QRect(110, 120, 181, 22))
        self.food1_cmb.setObjectName("food1_cmb")
        self.bev1_cmb = QtWidgets.QComboBox(self.page_2)
        self.bev1_cmb.setGeometry(QtCore.QRect(460, 120, 181, 22))
        self.bev1_cmb.setObjectName("bev1_cmb")
        self.delfood_btn = QtWidgets.QPushButton(self.page_2)
        self.delfood_btn.setGeometry(QtCore.QRect(150, 252, 111, 31))
        self.delfood_btn.setObjectName("delfood_btn")
        self.delbev_btn = QtWidgets.QPushButton(self.page_2)
        self.delbev_btn.setGeometry(QtCore.QRect(500, 250, 111, 31))
        self.delbev_btn.setObjectName("delbev_btn")
        self.foodpriceupt_btn = QtWidgets.QPushButton(self.page_2)
        self.foodpriceupt_btn.setGeometry(QtCore.QRect(160, 420, 101, 31))
        self.foodpriceupt_btn.setObjectName("foodpriceupt_btn")
        self.bevpriceupt_btn = QtWidgets.QPushButton(self.page_2)
        self.bevpriceupt_btn.setGeometry(QtCore.QRect(500, 420, 91, 31))
        self.bevpriceupt_btn.setObjectName("bevpriceupt_btn")
        self.food1price_edt = QtWidgets.QLineEdit(self.page_2)
        self.food1price_edt.setGeometry(QtCore.QRect(110, 370, 191, 20))
        self.food1price_edt.setObjectName("food1price_edt")
        self.bev1price_edt = QtWidgets.QLineEdit(self.page_2)
        self.bev1price_edt.setGeometry(QtCore.QRect(452, 370, 171, 20))
        self.bev1price_edt.setObjectName("bev1price_edt")
        self.delfoodbevbck_btn = QtWidgets.QPushButton(self.page_2)
        self.delfoodbevbck_btn.setGeometry(QtCore.QRect(340, 450, 75, 41))
        self.delfoodbevbck_btn.setObjectName("delfoodbevbck_btn")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#0000ff;\">CENTRAL PERK</span></p></body></html>"))
        self.usr_edt.setPlaceholderText(_translate("MainWindow", "Enter username"))
        self.pass_edt.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.lgn_btn.setText(_translate("MainWindow", "LOGIN"))
        self.reg_btn.setText(_translate("MainWindow", "REGISTER"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#00aa00;\">ADMINS ONLY!!!</span></p></body></html>"))
        self.nadmusr_edt.setPlaceholderText(_translate("MainWindow", "Enter username"))
        self.nadmpass_edt.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.nadmsub_btn.setText(_translate("MainWindow", "SUBMIT"))
        self.nadmbck_btn.setText(_translate("MainWindow", "BACK"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">MANAGING STAFF ONLY!</span></p></body></html>"))
        self.newcs_btn.setText(_translate("MainWindow", "NEW CUSTOMER"))
        self.uptcs_btn.setText(_translate("MainWindow", "UPDATE CUSTOMER"))
        self.delcs_btn.setText(_translate("MainWindow", "DELETE CUSTOMER"))
        self.uptf_btn.setText(_translate("MainWindow", "ADD FOOD/BEVERAGES"))
        self.ext_btn.setText(_translate("MainWindow", "EXIT"))
        self.dispcs_btn.setText(_translate("MainWindow", "DISPLAY ALL CUSTOMERS"))
        self.uptf1_btn.setText(_translate("MainWindow", "DELETE/UPDATE FOODITEMS"))
        self.csgraph_btn.setText(_translate("MainWindow", "DISPLAY CUSTOMER GRAPH"))
        self.foodgraph_btn.setText(_translate("MainWindow", "DISPLAY FOOD GRAPH"))
        self.bevgraph_btn.setText(_translate("MainWindow", "DISPLAY BEV GRAPH"))
        self.ncsname_edt.setPlaceholderText(_translate("MainWindow", "Enter Name"))
        self.ncsmbn_edt.setPlaceholderText(_translate("MainWindow", "Enter Mobile Number"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">NEW CUSTOMER</span></p></body></html>"))
        self.ncsadd_edt.setPlaceholderText(_translate("MainWindow", "Enter Address"))
        self.ncssub_btn.setText(_translate("MainWindow", "SUBMIT"))
        self.ncsbck_btn.setText(_translate("MainWindow", "BACK"))
        self.uptcsidsub_btn.setText(_translate("MainWindow", "SUBMIT"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00ff7f;\">UPDATE CUSTOMER</span></p></body></html>"))
        self.uptcsid_edt.setPlaceholderText(_translate("MainWindow", "Enter Customer id"))
        self.uptcsidbck_btn.setText(_translate("MainWindow", "BACK"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">FOOD/BEVERAGES</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline;\">FOOD</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline;\">BEVERAGES</span></p></body></html>"))
        self.foodadd_btn.setText(_translate("MainWindow", "ADD"))
        self.bevadd_btn.setText(_translate("MainWindow", "ADD"))
        self.fbbck_btn.setText(_translate("MainWindow", "BACK"))
        self.prcr_btn.setText(_translate("MainWindow", "PRINT CURRENT BILL"))
        self.uptcs_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Customer id:</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline;\">UPDATE FOOD/BEVERAGES</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:italic; text-decoration: underline;\">FOODS</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:italic; text-decoration: underline;\">BEVERAGES</span></p></body></html>"))
        self.nfoodname_edt.setPlaceholderText(_translate("MainWindow", "Enter new food"))
        self.nbevname_edt.setPlaceholderText(_translate("MainWindow", "Enter new beverage"))
        self.nfoodprice_edt.setPlaceholderText(_translate("MainWindow", "Enter price"))
        self.nbevprice_edt.setPlaceholderText(_translate("MainWindow", "Enter price"))
        self.nfoodsub_btn.setText(_translate("MainWindow", "SUBMIT"))
        self.nbevsub_btn.setText(_translate("MainWindow", "SUBMIT"))
        self.nfbbck_btn.setText(_translate("MainWindow", "BACK"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">DELETE CUSTOMER</span></p></body></html>"))
        self.delcs_edt.setPlaceholderText(_translate("MainWindow", "Enter customer id"))
        self.delcsid_btn.setText(_translate("MainWindow", "SUBMIT"))
        self.delbck_btn.setText(_translate("MainWindow", "BACK"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#55ffff;\">PRESENT CUSTOMERS</span></p></body></html>"))
        self.dispallcs_btn.setText(_translate("MainWindow", "SUBMIT"))
        self.dispallcsbck_btn.setText(_translate("MainWindow", "BACK"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00aa00;\">UPDATE/DELETE FOODITEMS</span></p></body></html>"))
        self.delfood_btn.setText(_translate("MainWindow", "DELETE"))
        self.delbev_btn.setText(_translate("MainWindow", "DELETE"))
        self.foodpriceupt_btn.setText(_translate("MainWindow", "UPDATE"))
        self.bevpriceupt_btn.setText(_translate("MainWindow", "UPDATE"))
        self.food1price_edt.setPlaceholderText(_translate("MainWindow", "Enter price"))
        self.bev1price_edt.setPlaceholderText(_translate("MainWindow", "Enter price"))
        self.delfoodbevbck_btn.setText(_translate("MainWindow", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

